# Generated by Django 5.2 on 2025-04-29 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='jumlah')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Harga per satuan', max_digits=15, null=True, verbose_name='harga beli')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tanggal masuk')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='tanggal kadaluarsa')),
            ],
            options={
                'verbose_name': 'Item Inventaris (Batch)',
                'verbose_name_plural': 'Item Inventaris (Batch)',
                'ordering': ['entry_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nama kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori Produk',
                'verbose_name_plural': 'Kategori Produk',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nama varian')),
                ('description', models.TextField(blank=True, null=True, verbose_name='deskripsi')),
                ('unit_of_measure', models.CharField(default='pcs', help_text='Contoh: pcs, box, rim, unit', max_length=20, verbose_name='satuan')),
            ],
            options={
                'verbose_name': 'Varian Produk',
                'verbose_name_plural': 'Varian Produk',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='nomor permintaan')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan (Menunggu Atasan Peminta)'), ('REJECTED_SPV1', 'Ditolak Atasan Peminta'), ('APPROVED_SPV1', 'Disetujui Atasan Peminta (Menunggu Atasan Operator)'), ('REJECTED_SPV2', 'Ditolak Atasan Operator'), ('APPROVED_SPV2', 'Disetujui Atasan Operator (Menunggu Operator)'), ('PROCESSING', 'Diproses Operator'), ('REJECTED_OPR', 'Ditolak Operator'), ('COMPLETED', 'Selesai (Menunggu Konfirmasi Terima)'), ('RECEIVED', 'Barang Diterima Peminta'), ('CANCELLED', 'Dibatalkan')], default='DRAFT', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat tanggal')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='diajukan tanggal')),
                ('supervisor1_decision_at', models.DateTimeField(blank=True, null=True, verbose_name='tanggal keputusan spv1')),
                ('supervisor1_rejection_reason', models.TextField(blank=True, null=True, verbose_name='alasan penolakan spv1')),
                ('supervisor2_decision_at', models.DateTimeField(blank=True, null=True, verbose_name='tanggal keputusan spv2')),
                ('supervisor2_rejection_reason', models.TextField(blank=True, null=True, verbose_name='alasan penolakan spv2')),
                ('operator_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='tanggal diproses operator')),
                ('operator_rejection_reason', models.TextField(blank=True, null=True, verbose_name='alasan penolakan operator')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='diterima peminta tanggal')),
            ],
            options={
                'verbose_name': 'Permintaan Barang',
                'verbose_name_plural': 'Permintaan Barang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='jumlah diminta')),
                ('quantity_approved_spv2', models.PositiveIntegerField(blank=True, null=True, verbose_name='jumlah disetujui Atasan Operator')),
                ('quantity_issued', models.PositiveIntegerField(default=0, verbose_name='jumlah dikeluarkan')),
            ],
            options={
                'verbose_name': 'Item Permintaan',
                'verbose_name_plural': 'Item Permintaan',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='waktu')),
                ('action', models.CharField(max_length=50, verbose_name='aksi')),
                ('status_from', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan (Menunggu Atasan Peminta)'), ('REJECTED_SPV1', 'Ditolak Atasan Peminta'), ('APPROVED_SPV1', 'Disetujui Atasan Peminta (Menunggu Atasan Operator)'), ('REJECTED_SPV2', 'Ditolak Atasan Operator'), ('APPROVED_SPV2', 'Disetujui Atasan Operator (Menunggu Operator)'), ('PROCESSING', 'Diproses Operator'), ('REJECTED_OPR', 'Ditolak Operator'), ('COMPLETED', 'Selesai (Menunggu Konfirmasi Terima)'), ('RECEIVED', 'Barang Diterima Peminta'), ('CANCELLED', 'Dibatalkan')], max_length=20, null=True, verbose_name='status dari')),
                ('status_to', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Diajukan (Menunggu Atasan Peminta)'), ('REJECTED_SPV1', 'Ditolak Atasan Peminta'), ('APPROVED_SPV1', 'Disetujui Atasan Peminta (Menunggu Atasan Operator)'), ('REJECTED_SPV2', 'Ditolak Atasan Operator'), ('APPROVED_SPV2', 'Disetujui Atasan Operator (Menunggu Operator)'), ('PROCESSING', 'Diproses Operator'), ('REJECTED_OPR', 'Ditolak Operator'), ('COMPLETED', 'Selesai (Menunggu Konfirmasi Terima)'), ('RECEIVED', 'Barang Diterima Peminta'), ('CANCELLED', 'Dibatalkan')], max_length=20, null=True, verbose_name='status ke')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='komentar/catatan')),
            ],
            options={
                'verbose_name': 'Log Permintaan',
                'verbose_name_plural': 'Log Permintaan',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SPMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spmb_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='nomor SPMB')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='diterbitkan tanggal')),
            ],
            options={
                'verbose_name': 'SPMB',
                'verbose_name_plural': 'SPMB',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOpnameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(verbose_name='jumlah sistem')),
                ('counted_quantity', models.IntegerField(verbose_name='jumlah hitung fisik')),
                ('difference', models.IntegerField(editable=False, verbose_name='selisih')),
                ('confirmation_status', models.CharField(choices=[('PENDING', 'Menunggu Konfirmasi'), ('MATCH', 'Dikonfirmasi (Sesuai)'), ('ADJUST', 'Dikonfirmasi (Perlu Penyesuaian)'), ('REJECTED', 'Ditolak (Perlu Investigasi)')], default='PENDING', max_length=10, verbose_name='status konfirmasi')),
                ('confirmation_notes', models.TextField(blank=True, null=True, verbose_name='catatan konfirmasi')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='dikonfirmasi tanggal')),
            ],
            options={
                'verbose_name': 'Item Stock Opname',
                'verbose_name_plural': 'Item Stock Opname',
                'ordering': ['opname_session', 'variant__name'],
            },
        ),
        migrations.CreateModel(
            name='StockOpnameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opname_date', models.DateField(default=django.utils.timezone.now, verbose_name='tanggal opname')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='stock_opname/%Y/%m/', verbose_name='file unggahan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat tanggal')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Konfirmasi Perbedaan'), ('COMPLETED', 'Selesai')], default='PENDING', max_length=20, verbose_name='status sesi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='catatan sesi')),
            ],
            options={
                'verbose_name': 'Sesi Stock Opname',
                'verbose_name_plural': 'Sesi Stock Opname',
                'ordering': ['-opname_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positif untuk IN/ADJUST+, Negatif untuk OUT/ADJUST-', verbose_name='jumlah')),
                ('transaction_type', models.CharField(choices=[('IN', 'Masuk'), ('OUT', 'Keluar'), ('ADJUST', 'Penyesuaian')], max_length=10, verbose_name='tipe transaksi')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='waktu transaksi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='catatan')),
            ],
            options={
                'verbose_name': 'Transaksi Stok',
                'verbose_name_plural': 'Transaksi Stok',
                'ordering': ['-timestamp'],
            },
        ),
    ]
