# Generated by Django 5.2 on 2025-04-29 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='ditambahkan oleh'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_level', serialize=False, to='inventory.productvariant', verbose_name='varian produk')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='total kuantitas')),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='ambang batas stok rendah')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='terakhir diperbarui')),
            ],
            options={
                'verbose_name': 'Level Stok',
                'verbose_name_plural': 'Level Stok',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.productcategory', verbose_name='kategori'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.productvariant', verbose_name='varian produk'),
        ),
        migrations.AddField(
            model_name='request',
            name='operator_processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests_opr', to=settings.AUTH_USER_MODEL, verbose_name='pemroses (Operator)'),
        ),
        migrations.AddField(
            model_name='request',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_made', to=settings.AUTH_USER_MODEL, verbose_name='peminta'),
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor1_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests_spv1', to=settings.AUTH_USER_MODEL, verbose_name='penyetuju (Atasan Peminta)'),
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor2_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests_spv2', to=settings.AUTH_USER_MODEL, verbose_name='penyetuju (Atasan Operator)'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.request', verbose_name='permintaan'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_in', to='inventory.productvariant', verbose_name='varian produk'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.request', verbose_name='permintaan'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='pengguna'),
        ),
        migrations.AddField(
            model_name='spmb',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spmb_issued', to=settings.AUTH_USER_MODEL, verbose_name='diterbitkan oleh (Operator)'),
        ),
        migrations.AddField(
            model_name='spmb',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spmb_document', to='inventory.request', verbose_name='permintaan terkait'),
        ),
        migrations.AddField(
            model_name='stockopnameitem',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_opname_items', to=settings.AUTH_USER_MODEL, verbose_name='dikonfirmasi oleh (Operator)'),
        ),
        migrations.AddField(
            model_name='stockopnameitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant', verbose_name='varian produk'),
        ),
        migrations.AddField(
            model_name='stockopnamesession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opname_sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh (Admin)'),
        ),
        migrations.AddField(
            model_name='stockopnameitem',
            name='opname_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockopnamesession', verbose_name='sesi opname'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem', verbose_name='item inventaris terkait'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.request', verbose_name='permintaan terkait'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_spmb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.spmb', verbose_name='SPMB terkait'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='pengguna'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productvariant', verbose_name='varian produk'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='requestitem',
            unique_together={('request', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='stockopnameitem',
            unique_together={('opname_session', 'variant')},
        ),
    ]
