# Generated by Django 5.2 on 2025-04-30 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCodeBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='kode barang (akhir)')),
                ('base_description', models.TextField(verbose_name='uraian barang (dasar)')),
                ('account_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='kode akun')),
                ('account_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='uraian akun')),
            ],
            options={
                'verbose_name': 'Kode Barang Dasar',
                'verbose_name_plural': 'Kode Barang Dasar',
                'ordering': ['sub_kelompok', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ItemCodeGolongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='kode golongan')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='uraian golongan')),
            ],
            options={
                'verbose_name': 'Golongan Barang',
                'verbose_name_plural': 'Golongan Barang',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['base_item_code', 'specific_code'], 'verbose_name': 'Varian Produk Spesifik', 'verbose_name_plural': 'Varian Produk Spesifik'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['variant__full_code'], 'verbose_name': 'Level Stok', 'verbose_name_plural': 'Level Stok'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='full_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='kode barang lengkap'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='specific_code',
            field=models.CharField(blank=True, editable=False, help_text='3 digit unik per kode barang dasar, di-generate otomatis.', max_length=3, verbose_name='kode spesifik'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='inventory.productvariant', verbose_name='varian produk spesifik'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='deskripsi tambahan'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='Contoh: Aspal Pertamina 60/70, Pulpen Snowman V5 Hitam', max_length=150, verbose_name='nama varian spesifik'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock_level', serialize=False, to='inventory.productvariant', verbose_name='varian produk spesifik'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_item_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='inventory.itemcodebarang', verbose_name='kode barang dasar'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('base_item_code', 'name')},
        ),
        migrations.CreateModel(
            name='ItemCodeBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='kode bidang')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='uraian bidang')),
                ('golongan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidang_set', to='inventory.itemcodegolongan', verbose_name='golongan')),
            ],
            options={
                'verbose_name': 'Bidang Barang',
                'verbose_name_plural': 'Bidang Barang',
                'ordering': ['golongan__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ItemCodeKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='kode kelompok')),
                ('description', models.TextField(blank=True, null=True, verbose_name='uraian kelompok')),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelompok_set', to='inventory.itemcodebidang')),
            ],
            options={
                'verbose_name': 'Kode Kelompok Barang',
                'verbose_name_plural': 'Kode Kelompok Barang',
                'ordering': ['bidang__golongan__code', 'bidang__code', 'code'],
                'unique_together': {('bidang', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemCodeSubKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='kode sub kelompok')),
                ('base_description', models.TextField(verbose_name='uraian sub kelompok (dasar)')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkelompok_set', to='inventory.itemcodekelompok')),
            ],
            options={
                'verbose_name': 'Kode Sub Kelompok Barang',
                'verbose_name_plural': 'Kode Sub Kelompok Barang',
                'ordering': ['kelompok__bidang__golongan__code', 'kelompok__bidang__code', 'kelompok__code', 'code'],
                'unique_together': {('kelompok', 'code')},
            },
        ),
        migrations.AddField(
            model_name='itemcodebarang',
            name='sub_kelompok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_set', to='inventory.itemcodesubkelompok'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True, verbose_name='nomor kuitansi/PO')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nama pemasok')),
                ('receipt_date', models.DateField(verbose_name='tanggal kuitansi/pembelian')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='file unggahan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='diunggah tanggal')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL, verbose_name='diunggah oleh')),
            ],
            options={
                'verbose_name': 'Kuitansi Pembelian',
                'verbose_name_plural': 'Kuitansi Pembelian',
                'ordering': ['-receipt_date', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.receipt', verbose_name='kuitansi terkait'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='itemcodebarang',
            unique_together={('sub_kelompok', 'code')},
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
