# Generated by Django 5.2 on 2025-04-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemcodebarang_itemcodegolongan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['base_item_code', 'type_name', 'specific_code'], 'verbose_name': 'Varian Produk Spesifik', 'verbose_name_plural': 'Varian Produk Spesifik'},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='type_name',
            field=models.CharField(db_index=True, default='', help_text='Contoh: Pulpen, Pensil, Kertas, dll', max_length=100, verbose_name='nama jenis'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('base_item_code', 'type_name', 'name')},
        ),
    ]
