# Generated by Django 5.2 on 2025-04-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcodebarang',
            options={'ordering': ['full_base_code'], 'verbose_name': 'Kode Barang Dasar', 'verbose_name_plural': 'Kode Barang Dasar'},
        ),
        migrations.AddField(
            model_name='itemcodebarang',
            name='full_base_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='kode barang lengkap'),
        ),
    ]
