# Generated by Django 5.2 on 2025-04-30 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_itemcodebarang_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcodebidang',
            options={'ordering': ['golongan__code', 'code'], 'verbose_name': 'Kode Bidang Barang', 'verbose_name_plural': 'Kode Bidang Barang'},
        ),
        migrations.AlterModelOptions(
            name='itemcodegolongan',
            options={'ordering': ['code'], 'verbose_name': 'Kode Golongan Barang', 'verbose_name_plural': 'Kode Golongan Barang'},
        ),
        migrations.AlterModelOptions(
            name='stockopnameitem',
            options={'ordering': ['opname_session', 'variant__full_code'], 'verbose_name': 'Item Stock Opname', 'verbose_name_plural': 'Item Stock Opname'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.receipt', verbose_name='kuitansi terkait'),
        ),
        migrations.AlterField(
            model_name='itemcodebarang',
            name='full_base_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, unique=True, verbose_name='kode barang dasar lengkap'),
        ),
        migrations.AlterField(
            model_name='itemcodebidang',
            name='code',
            field=models.CharField(max_length=10, verbose_name='kode bidang'),
        ),
        migrations.AlterField(
            model_name='itemcodebidang',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='uraian bidang'),
        ),
        migrations.AlterField(
            model_name='itemcodebidang',
            name='golongan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidang_set', to='inventory.itemcodegolongan'),
        ),
        migrations.AlterField(
            model_name='itemcodegolongan',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='uraian golongan'),
        ),
        migrations.AlterField(
            model_name='itemcodekelompok',
            name='code',
            field=models.CharField(max_length=10, verbose_name='kode kelompok'),
        ),
        migrations.AlterField(
            model_name='itemcodesubkelompok',
            name='code',
            field=models.CharField(max_length=15, verbose_name='kode sub kelompok'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(help_text='Contoh: Snowman 0.5 Hitam, Faber-Castell 2B, Lifebuoy Mild Care', max_length=150, verbose_name='nama spesifik (merk/tipe)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='type_name',
            field=models.CharField(db_index=True, help_text='Contoh: Pulpen, Pensil, Sabun Cuci Tangan', max_length=100, verbose_name='jenis barang'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='unit_of_measure',
            field=models.CharField(default='pcs', help_text='Contoh: pcs, box, rim, unit, kg, liter', max_length=20, verbose_name='satuan'),
        ),
        migrations.AlterUniqueTogether(
            name='itemcodebidang',
            unique_together={('golongan', 'code')},
        ),
    ]
