# Generated by Django 5.2 on 2025-05-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_itemcodebidang_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Nilai barcode unik untuk varian ini, biasanya sama dengan Kode Lengkap.', max_length=50, unique=True, verbose_name='barcode'),
        ),
    ]
