# Generated by Django 5.2 on 2025-04-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_code',
            field=models.CharField(blank=True, help_text='Contoh: WBC.051', max_length=10, null=True, verbose_name='kode bagian/bidang'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PEMINTA', 'Peminta Barang'), ('ATASAN_PEMINTA', 'Atasan Peminta Barang'), ('OPERATOR', 'Operator Persediaan'), ('ATASAN_OPERATOR', 'Atasan Operator Persediaan'), ('ADMIN', 'Administrator')], default='PEMINTA', max_length=20, verbose_name='Role'),
        ),
    ]
